sudo: false

language: c

os:
  - linux

env:
  - PATH=$HOME/.nimble/bin:$PATH

cache:
  directories:
    - $HOME/.nimble
    - $HOME/.choosenim

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev

before_install:
  - if [ ! -e $HOME/.nimble/bin/nim ]; then curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh && bash init.sh -y && choosenim "#v0.20.0"; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - echo PATH:${PATH}
  - set +e

script:
  - echo script

after_success:
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in coc_radar_key.enc -out coc_radar_key -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com"                >> ~/.ssh/config
  - echo -e "\n\tUser git"                   >> ~/.ssh/config
  - echo -e "\n\tStrictHostKeyChecking no"   >> ~/.ssh/config
  - echo -e "\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
  - echo -e "\n\tIdentitiesOnly yes"         >> ~/.ssh/config
  - echo -e "\n\tForwardAgent yes"           >> ~/.ssh/config
  - git config --global user.email "jiroron666@gmail.com"
  - git config --global user.name "jiro4989"
  - git clone https://github.com/jiro4989/coc.git
  - cd coc
  - nimble install -Y
  - coc -h
  - cd ..
  - nimble install -Y
  - coc_radar -h
  - ./deploy.sh
