sudo: false

language: c

os:
  - linux

env:
  - PATH=$HOME/.nimble/bin:$PATH

cache:
  directories:
    - $HOME/.nimble
    - $HOME/.choosenim

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev
      - npm

before_install:
  - if [ ! -e $HOME/.nimble/bin/nim ]; then curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh && bash init.sh -y && choosenim "#v0.20.0"; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - echo PATH:${PATH}
  - set +e

script:
  - git clone https://github.com/jiro4989/coc.git
  - cd coc
  - nimble install -Y
  - coc -h
  - cd ..
  - nimble install -Y
  - coc_radar -h
  - npm i
  - npm run build

before_deploy:
  - ./deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
