sudo: false

language: c

os:
  - linux

env:
  - PATH=$HOME/.nimble/bin:$PATH

cache:
  directories:
    - $HOME/.nimble
    - $HOME/.choosenim

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libsdl1.2-dev
      - libgc-dev
      - libsfml-dev
      - npm

before_install:
  - if [ ! -e $HOME/.nimble/bin/nim ]; then curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh && bash init.sh -y; choosenim update stable; fi

before_script:
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - echo PATH:${PATH}
  - set +e

script:
  - nimble install -Y
  - coc_radar -h
  - npm i
  - npm run build
  - npm test

before_deploy:
  - ./deploy.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: NXa6pQfkWufCFKroMmKZM9qHzRMTloACcoyZ7kJHQDC225hr34PCa9EK45RlbKPlcu3LsRqGqGtGxZrrTXcwmOm9npFtrSxZuUx7ZN4aSYNBOXLnjNmM93NQ9za8K8c4857HtafglpLokFNcekbUCh5/Vm9qaofPV6ZcEEYN/tfBohbNktexqaNFd6q7sEpfp6As4r2qdw4D9jlFKrDwafOxuMl2Y6I4uPmj3DTyiwGQNHFOtQ3+vkVuEWTndpGOBqPUubvHMawD0ebu7PXMc2Z8eqrvGEPg/sPHAPt37feiBt0FwEHSu73R0+lC62+RKiP80E1byQx0GqFRYbfHlpQPaQKSRWFN2/W1kDiNWtf8bjQKcoJ8OU2xC9Ah+uUIwvdtwh0dYRyLtqOFhlXg+mxoU9Jp4J+akUoF5A0SQPq1mEC0cs5JiawjklOr6Mo5t/wLKWujMVgat5ihNswLZgD4A2XkKqrVfPfECNwpeXAYi1JgzsPWihjhuRKJbZbcBKbbvAUN/NeitIHVRMWZHoC071gFVTuQiA8vzwsJEeL5psUv1xi0TgY45nh6n1kcHdJupscoUr+TWxmeyYYVAhKoU2p3bbZVxsCzzJwMjBFFooeS9cmo4DMdA6jQDQDIIY4Vuvv2Lgx5vctt2JcECH70w0mGxo7g6k0jI5XruCw=
  keep-history: true
  local-dir: build
  target-branch: gh-pages
  on:
    branch: master
